title: Anime Mania
email: null@gmail.com
description: "Anime Mania"
baseurl: "/"
url: "https://animemaniawsp.github.io"
twitter_username: best magisk module
github_username:  best magisk
author: Anime Mania


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
